### ISSUE TITLE
Visual fixes

### ISSUE THREAD

**Issue by rtxm** [Net-ng/kansha#147]
* Placeholders in inputs/textareas should be lighter (color);
* when the user is typing in an input/textarea the color of the text should be the same as the final rendering;
* on the home page, on small screens, the main menu is hanging;
* badges should be lighter (color);
* when we click on a card's description, the editor should get the focus;
* suppress the thick border of the editor; make it more integrated in the style of Kansha;
* cover management: the style of the tick should be the same as the other icons'; The user experience should be more like in kansha v2 prototype;
* the vote badge should not be clickable;
* drop slots of cards should appear lowered;
* replace « Public templates » by « Shared templates »;
* favicon is ugly;
* on card editor, the column title should follow the card title on the same line;
* test on Safari.

**Comment by vrialland** [comment]
- [x] Placeholders in inputs/textareas should be lighter (color);
- [x] when the user is typing in an input/textarea the color of the text should be the same as the final rendering;
- [x] on the home page, on small screens, the main menu is hanging;
- [x] badges should be lighter (color);
- [x] when we click on a card's description, the editor should get the focus;
- [x] suppress the thick border of the editor; make it more integrated in the style of Kansha;
* cover management: the style of the tick should be the same as the other icons'; The user experience should be more like in kansha v2 prototype;
* the vote badge should not be clickable;
* drop slots of cards should appear lowered;
- [x] replace « Public templates » by « Shared templates »;
* favicon is ugly;
* on card editor, the column title should follow the card title on the same line;
* test on Safari.

**Comment by rtxm** [comment]
The file upload wait overlay is not closed anymore when upload is complete.
