### ISSUE TITLE
Display public boards on the home page

### ISSUE THREAD

**Issue by daamien** [Net-ng/kansha#164]
When a board is public, people can access it directly from the URL but they can't see it among the available boards on their homepage.

It would be great to have on option in the board preference to allow users to see a public board

"Display this board on the homepage : Yes/No"

**Comment by nagareproject** [comment]
:+1: for the feature.

I personally see the UI more like a "favorite" / "starred" design, also available on the private boards to sort them by importance

**Comment by daamien** [comment]
What's the meaning of the "Needs User Story" tag ? Do you want more details ?

**Comment by rtxm** [comment]
The tag means the feature request deserves a complete user story. We have to think about how it should work, from a user experience point of view, in detail, taking all the implications into account.
For example, does the user chooses what public boards appear on her home page by starring them from a "discover" page? Etc…

**Comment by daamien** [comment]
Ok thanks @rtxm for the clarification.

_Here's some context : _

We're a group of 20+ employees working together in 9 teams. Each team has one board (sometimes more). Each team member is a "member" of the board. Most of the boards are public and every employee can read a public board. 

_Our problem:_

When you're a new employee, you don't belong to any team. Technically you have read access to most of the board but you can't see them because they're not displayed on your home page. You only see the board when you're a member of it.

_ What we want:_

We want the homepage to display all the boards that the user can read, not just the boards that the user belongs to.

**Comment by rtxm** [comment]
Hello,

in your first message, you say you'd like to have a preference settings to make the public board visible. You mean, the manager of the board decides whether the public board appears on the homepage of all users?

**Comment by daamien** [comment]
yes exactly. 

In the version we're using (1.0.5) the settings page is very confusing about this 

The option table is "Visibilité : Définissez si le board est privé ou public." with a "Privé/Public" button (sorry for non-French readers)

To me, this option does not define the "visibility" of a board, it defines the access right, i.e  "Is this board accessible to anyone or restricted to member only" 

The visibility is a slightly different question: "Is this board visible for every user or  only visible to its member ?"

I'd be ok if those 2 questions were merged so that: 
* A- Public Boards are automatically visible to every kansha user
* B- Private Boards are only visible to the members

This seems to me like the "Right Thing To Do" and it's my prefered solution but the point A is a breach of the current logic and some user might be confused by the change

So my proposition is to add another option in the settings page just below the visibilty question.

"Display this board on the homepage ? Yes/No"

* if the board is private, the question is disabled and the value is forced at "No" (it has no sense to make a private board visible to everybody) 

* if the board is public, the question is enabled and the value is by default at "Yes"

On the home page, you display to the users all the board where's he's a member AND the public boards where the "display" option is set to "Yes"

**Comment by rtxm** [comment]
The setting reminds me a kind of share option:

Visibility
  - private
  - url (current meaning of public, anyone with the url can view its content)
  - public (visible and readable by everybody)

That would avoid to offer a conditional option (publish on homepages). 

What do you think?

**Comment by rtxm** [comment]
or private/public/shared to avoid confusing current users by changing the meaning of public.

**Comment by daamien** [comment]
private/public/shared is perfect for us
