### ISSUE TITLE
Checklists: the input to add an item shoud not remain open when not needed.

### ISSUE THREAD

**Issue by rtxm** [Net-ng/kansha#186]
### US 1
- The user clicks on a card to open it.
- The user adds a checklist.
- The input to add an item is open. It has an **add** button only.
- The input remains open after an item is added and remains so until the card popin is closed.
### US 2
- The user clicks on a card to open it.
- There is a checklist already on it.
- There is no input visible to add an item. There is a **+** button instead.
- The user clicks on the **+** button.
- The **+** button becomes an input to add an item. It has an **add** button only.
- The input remains open after an item is added and remains so until the card popin is closed.

**Comment by rtxm** [comment]
@blugand, @nagareproject, can you please validate these User Stories ?

**Comment by blugand** [comment]
how do you add a second item ? + button is always visible ?

'The input remains open after an item is added and remains so until the card popin is closed' I'm not shure to see exactly what you mean. A mockup could explain it. 

For example : I add 3 new items on an existing  checklist.
But I realize that i've to delete Item 2
Is it possible without having to exist the card and re open it ?

**Comment by rtxm** [comment]
It is the same behavior as today. You can delete items at anytime. The only difference is that we won't show the "add item" input by default anymore. We'llshow it when:

* you create a new checklist;
* you click the **+** button below an existing checklist.

Once the input is visible, it will work as today and stay visible until you close the card popin.

**Comment by Net-ng** [comment]
> Le 20 janv. 2016 à 19:03, Romuald Texier-Marcadé <notifications@github.com> a écrit :
> 
> It is the same behavior as today. You can delete items at anytime. The only difference is that we won't show the "add item" input by default anymore. We'llshow it when:
> 
> 	• you create a new checklist;
> 	• you click the + button below an existing checklist.
> Once the input is visible, it will work as today and stay visible until you close the card popin.

I don’t know the technical difficulty to display the « add item » when a new
checklist is created and to let it stay displayed during all the time the popup
stays visible.

These ergonomic choices are fine but if they require too much effort, I’d be happy
with the classic workflow: click on ‘+’ each time to display the « add item » input
which is then closed on « Save ».
