### ISSUE TITLE
Responsive design to change

### ISSUE THREAD

**Issue by ephilippot** [Net-ng/kansha#19]
The responsive design for Kansha home page must be reviewed. With a page in addition to 1300px wide content already fail over a single column.

![screen shot 09-10-15 at 04 59 pm](https://cloud.githubusercontent.com/assets/12171067/9791833/60551398-57dd-11e5-92f8-d3d8642ab985.PNG)

**Comment by rtxm** [comment]
Fixed in e7f69b611691fb67806cb695ab556dc66b46281e.
