### ISSUE TITLE
Viewing and Hiding week numbers

### ISSUE THREAD

**Issue by Net-ng** [Net-ng/kansha#20]
We would like to display or hide week numbers on the calendar view :+1: 

![calendrier](https://cloud.githubusercontent.com/assets/11835925/9792206/3840cc2e-57df-11e5-90c1-77fa83a139f8.PNG)

and also on the input interface of a deadline :

![echeance](https://cloud.githubusercontent.com/assets/11835925/9792194/2b11687e-57df-11e5-82c0-cbaf8415811b.PNG)

Take care : in the USA, the week number changes every Sunday and the rest of the world it changes every Monday.

**Comment by Reigel** [comment]
I'll give it a try.
