### ISSUE TITLE
PostgreSQL has a nice JSON datatype

### ISSUE THREAD

**Issue by daamien** [Net-ng/kansha#207]
I see you're storing JSON directly into PostgreSQL, for instance in the history.data field. 

Since 9.2, PostgreSQL has a specific JSON datatype and a bunch of related operators

http://www.postgresql.org/docs/9.5/static/datatype-json.html
http://www.postgresql.org/docs/9.5/static/functions-json.html

That means you can create an index on a JSON field and manipulate the data directly with Postgres. 

Also you're using the VARCHAR(255) type in some tables. PostgreSQL treats VARCHAR(x) just like a TEXT type. So VARCHAR is not an optimization and it won't save any space.

**Comment by rtxm** [comment]
We try to keep kansha "database agnostic". Some field type (e.g. VARCHAR) are used to ensure compatibility with some particular databases (there are still people using MySQL/MariaDB out there). We avoid using database specific fields.

**Comment by daamien** [comment]
ok
