### ISSUE TITLE
Can't create cover

### ISSUE THREAD

**Issue by blugand** [Net-ng/kansha#224]
When you add a picture as a file in a card and then select 'configure cover' for the first time, the button 'Create Cover' is under the picture ....
![chrome_2016-06-15_15-47-11](https://cloud.githubusercontent.com/assets/13645313/16082086/9d228b02-3310-11e6-9db8-e985377ecf38.png)

**Comment by rtxm** [comment]
Can't reproduce. Might have been fixed already.
