### ISSUE TITLE
Kansha is unasable with Microsoft Edge

### ISSUE THREAD

**Issue by blugand** [Net-ng/kansha#227]
Version 1.0.8 dev

When you try to open a card, nothing happens, cpu consumption increases, you have to kill the browser ...

**Comment by rtxm** [comment]
This is a known  Microsoft Edge bug: https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=microsoft+edge+hangs+OR%C2%A0freezes

**Comment by vrialland** [comment]
It seems to be linked with the search feature.
