### ISSUE TITLE
Fresh install according to docs - erorrs

### ISSUE THREAD

**Issue by Gman1988** [Net-ng/kansha#230]
Hi i tried to install it from scratch but there is problem when i invoking 

<VENV_DIR>/bin/nagare-admin serve -c </path/to/your/kansha.cfg>

It hangs on information about that it cannot import _dummy_thread.

I read about it and i was renamed to dummy_thead.

Can you provide me full working already install instruction without docker ?

I want to run it on with nginx.

**Comment by bcroq** [comment]
The `import _dummy_thread` error is a [flup ](https://pypi.python.org/pypi/flup) related error.

Try installing flup 1.0.2 with

```shell

easy_install flup==1.0.2
```
