### ISSUE TITLE
LDAP - Activ Directory -> CRITICAL - LDAP server down

### ISSUE THREAD

**Issue by Gman1988** [Net-ng/kansha#254]
Hi i have config as below:

[[ldaplogin]]
activated = on
server = 192.168.4.1
users_base_dn = "DC=example,DC=com"
schema = kansha.authentication.ldap.ldap_auth:ADLDAPAuth

And after start of app when i try to log using Activ Directory credentials i have error:
CRITICAL - LDAP server down

I have the same config in other apps and its working.

An you have any advice ?

**Comment by rtxm** [comment]
Hello!

Maybe your directory is not listening to the default port (389).

You can give a port with the ``port = `` directive (I'm going to add that to the docs).

**Comment by rtxm** [comment]
I'm closing this issue now. Reopen it if the issue still persists.
