### ISSUE TITLE
Unicode mismatch on signup form submission

### ISSUE THREAD

**Issue by haxwithaxe** [Net-ng/kansha#285]
When submitting the signup form on a fresh installation I get an empty response to the browser and the following exceptions.
```
/opt/stackless/lib/python2.7/site-packages/SQLAlchemy-1.2.4-py2.7-linux-x86_64.egg/sqlalchemy/sql/sqltypes.py:226: SAWarning: Unicode type received non-unicode bind param value 'en'. (this warning may be suppressed after 10 occurrences)
/opt/stackless/lib/python2.7/site-packages/SQLAlchemy-1.2.4-py2.7-linux-x86_64.egg/sqlalchemy/sql/sqltypes.py:226: SAWarning: Unicode type received non-unicode bind param value 'email_confirmation'. (this warning may be suppressed after 10 occurrences)
```

This happens when building from the v2.0.7 tag and master.
Am I missing something?

**Comment by bcroq** [comment]
These messages are warnings from SQLAlchemy, not exceptions. But it doesn't mean there is no problem.

Do you get other messages from the application or in the browser console?

**Comment by haxwithaxe** [comment]
This is the entire console output.
```
hax@lucky:~/d/kansha ((tags/v2.0.7) *%)$ docker run -it -p 8080:8080 kansha_kansha
+ /opt/stackless/bin/nagare-admin serve --port 8080 --host 0.0.0.0 kansha
Application 'app kansha' registered as '/'
Application 'app kansha' registered as '/kansha'
03/11/18 15:04:17 -serving on 0.0.0.0:8080 view at http://127.0.0.1:8080
/opt/stackless/lib/python2.7/site-packages/SQLAlchemy-1.2.4-py2.7-linux-x86_64.egg/sqlalchemy/sql/sqltypes.py:226: SAWarning: Unicode type received non-unicode bind param value 'en'. (this warning may be suppressed after 10 occurrences)
/opt/stackless/lib/python2.7/site-packages/SQLAlchemy-1.2.4-py2.7-linux-x86_64.egg/sqlalchemy/sql/sqltypes.py:226: SAWarning: Unicode type received non-unicode bind param value 'email_confirmation'. (this warning may be suppressed after 10 occurrences)

```
Attached is a screenshot or the whole end state.
![2018-03-11-110603_1920x1080_scrot](https://user-images.githubusercontent.com/111051/37255003-81f19904-251c-11e8-987c-404ab22a2075.png)

**Comment by bcroq** [comment]
@rtxm this error occurs when Kansha tries to send the "Confirm user registration" mail but cannot connect to the SMTP server

@haxwithaxe by default, Kansha's configuration in the netng/kansha docker image set the SMTP relay to localhost:25 which is certainly not the right configuration for you

**Comment by haxwithaxe** [comment]
Thanks. Works now.
