### ISSUE TITLE
Display chips labels on card form

### ISSUE THREAD

**Issue by ephilippot** [Net-ng/kansha#32]
On the card form, displays card labels and color...

![screen shot 09-14-15 at 11 12 am](https://cloud.githubusercontent.com/assets/12171067/9846297/79f8d8a6-5ad1-11e5-9887-594e26dddcee.PNG)

...and not only their color : 

![screen shot 09-14-15 at 11 02 am](https://cloud.githubusercontent.com/assets/12171067/9846119/2d87283e-5ad0-11e5-92a3-2ba186200ddf.PNG)

**Comment by droodle** [comment]
I'm working on it
