### ISSUE TITLE
Confirm message and due date

### ISSUE THREAD

**Issue by ephilippot** [Net-ng/kansha#34]
Display a confirm message before deleting a list.

When a card already has a due date displayed...

![screen shot 09-14-15 at 11 25 am](https://cloud.githubusercontent.com/assets/12171067/9846579/4967922a-5ad3-11e5-96f3-25b8edf38578.PNG)

...we should change it directly when we click on it.

**Comment by nagareproject** [comment]
:-1: for direct interaction to the badges of the cards
