### ISSUE TITLE
Bad footer position

### ISSUE THREAD

**Issue by droodle** [Net-ng/kansha#35]
On the login screen, the footer should stick to the bottom of the page when resizing the browser window. See screenshot.
![footer](https://cloud.githubusercontent.com/assets/1867537/9846824/076548d4-5ad5-11e5-8aa8-1bcd97c92fac.png)

**Comment by rtxm** [comment]
It happens below 1370px. Just remove the .credits entry completely from @media (max-width: 1370px).
