### ISSUE TITLE
Smartphone view - Reduce tab size and input length

### ISSUE THREAD

**Issue by ephilippot** [Net-ng/kansha#45]
All tabs should be on the same line here :

![screenshot_2015-09-17-16-14-20](https://cloud.githubusercontent.com/assets/12171067/9935606/ef6ed2ce-5d57-11e5-8d59-17a7283fa471.png)

And input length :

![screenshot_2015-09-17-16-36-22](https://cloud.githubusercontent.com/assets/12171067/9936122/bf1931d4-5d5a-11e5-853f-0856e89c0c6a.png)

**Comment by droodle** [comment]
I am working on it
