### ISSUE TITLE
Can't delete file of my card.

### ISSUE THREAD

**Issue by ephilippot** [Net-ng/kansha#47]
On my card i can't delete a file/image if I already have clicked on its "Make cover" link. I must close and open the card form again to access the Delete action.

**Comment by rtxm** [comment]
I can not reproduce. On which browser/OS did you experience the behavior you describe?

**Comment by rtxm** [comment]
Well, the exact procedure to reproduce the bug is:
* open a card
* upload image
* click image
* click set cover
* don't click "done", but close the popin (by clicking the cross in the upper right corner, for example)
