### ISSUE TITLE
Smartphone views - Design flaw

### ISSUE THREAD

**Issue by ephilippot** [Net-ng/kansha#54]
The search magnifying glass should not be displayed :

![screenshot_2015-09-15-17-15-58](https://cloud.githubusercontent.com/assets/12171067/9959597/7e21a056-5e15-11e5-9df9-a1f21c38b100.png)

Different icon should be used to display "export board" action :

![screen shot 09-15-15 at 05 22 pm](https://cloud.githubusercontent.com/assets/12171067/9959639/cfd47d24-5e15-11e5-9308-d1f120f84455.PNG)

The "SIGN IN" and "SIGN IN WITH LDAP" buttons must have the same design, even in smartphone view. The good ones : 

![screen shot 09-15-15 at 05 24 pm 001](https://cloud.githubusercontent.com/assets/12171067/9960842/5788ba8a-5e1d-11e5-9079-97effbf0e0c5.PNG)

and

![screen shot 09-15-15 at 05 24 pm](https://cloud.githubusercontent.com/assets/12171067/9960846/5bb00848-5e1d-11e5-84ba-7a244d90dadf.PNG)

**Comment by blugand** [comment]
![screenshot_20160624-152020](https://cloud.githubusercontent.com/assets/13645313/16339075/f53ed6d0-3a20-11e6-8353-9c499934d2f1.png)
![screenshot_20160624-152035](https://cloud.githubusercontent.com/assets/13645313/16339076/f54082d2-3a20-11e6-966e-26747e5b2142.png)
![screenshot_20160624-151420](https://cloud.githubusercontent.com/assets/13645313/16339077/f54275ba-3a20-11e6-8d4e-99f025114608.png)
![screenshot_20160624-151706](https://cloud.githubusercontent.com/assets/13645313/16339078/f542b67e-3a20-11e6-84ad-a2fa87010738.png)
![screenshot_20160624-151926](https://cloud.githubusercontent.com/assets/13645313/16339079/f5458296-3a20-11e6-8f5f-704d1fb89ede.png)
![screenshot_20160624-151944](https://cloud.githubusercontent.com/assets/13645313/16339080/f55a0108-3a20-11e6-84d1-cf9b50a31e8a.png)
