### ISSUE TITLE
Simplify styles

### ISSUE THREAD

**Issue by rtxm** [Net-ng/kansha#79]
## Objective 

We aim at a clean, minimal set of CSS files for Kansha **and** a clean, flat and consistent style throughout the application.

## User experience

* Reduce the number of colors. For example, we don't need so many levels of gray
* Make the design flat (the simpler, the better):
   * get rid of gradients
   * don't put shadows inside inputs or text areas
   * remove shadows around elements that are not active
   * replace sprites and icons by fonts
   * don't emboss emblems when hovering over cards
   * remove useless crosses in pop-ups
   * remove double-borders

![screenshot from 2015-10-23 17-35-32](https://cloud.githubusercontent.com/assets/7592443/10698371/f8689f66-79b0-11e5-95d9-ecbfbc883cd1.png)

## CSS organisation and guidelines
 
* General: http://kansha.readthedocs.org/en/stable/contribute.html#fix-bugs-and-code-new-features In particular **simplify** and avoid over-qualification (at most 2 levels if possible, never more than 3)
* Distinguish structural CSS (element layout, responsiveness) from "cosmetic" CSS (put them in different files)
* Put CSS *specific* to each environment (home, board, login…) in a different set of (structural, cosmetic) files. Put common CSS in its own set:
  * at the folder `static/css/themes`:
       * Common structural/functional CSS `kansha.css` and font definitions `fonts.css`
       * Structural CSS for each environment `login.css`, `board.css`, `home.css`
  * in a subfolder `static/css/themes/kansha_flat`:
       * Common styles in `kansha.css`
       * Styles for each environment `login.css`, `board.css`, `home.css`
   * at the root of `static/css`, it should only remain bootstrap, knacss and ckeditor.
* Update the views to include the appropriate files in the right order (struct common, struct env, styles common, styles env)
* Concerning the CSS for boards, lists and cards, make sections in your CSS files to easily find each object's styles. Make subsections to separate core CSS (e.g the card/list/board itself) from the CSS of features (e.g. tags on cards, search on boards, covers, comments…)

**Comment by vrialland** [comment]
I'm on it
