### ISSUE TITLE
Is bootstrap really necessary?

### ISSUE THREAD

**Issue by rtxm** [Net-ng/kansha#80]
It looks like we hardly use bootstrap at all, or just to reset the styles. In that case, why not use the lighter knacss used on the login page and get rid of boostrap to speed up page loading a bit?

**Comment by nagareproject** [comment]
:+1: I'm curious to see why we even use 'knacss' on the login page

**Comment by rtxm** [comment]
Yes, let's investigate that too. 
What have you found @vrialland?

**Comment by vrialland** [comment]
Bootstrap's usage:

- CSS reset
- Grids are used on the homepage (menu | boards) and when editing a card (contents | menu)
- Buttons styles and associated glyphs
- Progress bar in checklists

Knacss is used as a reset CSS on the login page and I removed Bootstrap in #79.
