### ISSUE TITLE
Create board from a template

### ISSUE THREAD

**Issue by rtxm** [Net-ng/kansha#86]
## Actual state

If a template directory is configured, all template files present in it are automatically loaded and boards created upon user creation (actually, at first login).

When a user creates a new board, a hard-coded template is used: three lists *Todo*, *Doing*, *Done*.

## New expected behavior

Don't automatically create boards from templates upon first login. Instead, let the user create boards from the availble templates, as detailed below. No more hard-coded templates.

On their homepage, users can create new boards. In order to do so, a drop-down menu of all available templates let them chose the template they wish to start from. No more text input, the title of the board can be modified later, on the board itself.

In the dropdown menu, templates are identified by their titles, not their filenames.

When the user clicks the *Create* button near the dropdown, a new board is created from the selected template, and the user is redirected to the new board.

Provide some default templates into the distribution (at least, the *Todo*, *Doing*, *Done* template). The shipped templates are always prepended to the list of templates found in the configured template directory.

## Technical notes

Use a kind of delegation pattern: each level (board, column, card) is responsible for configuring itself for its own JSON fragment.
 
* Board configures itself and create columns, passing to each column its JSON fragment ;
* Column configures itself and create cards, passing to each column its JSON fragment ;
* …

**Comment by vrialland** [comment]
See #97
