### ISSUE TITLE
Save a board as a template

### ISSUE THREAD

**Issue by rtxm** [Net-ng/kansha#87]
## Expected behavior

If a custom template directory is configured, we allow users to save the current board as a template. The template becomes available to all users.

On a board, in the board menu, a new entry is available for board owners: *Save as template*.
When a user clicks on that entry, a pop-up appears asking whether the template is personnal or public.
The new template appears in the list to create boards from on the user's home and, if public, on all users'.

## Technical notes

Use a kind of delegation pattern: each level (board, column, card) is responsible for exporting its own JSON fragment.

Use AssetManager to store templates.
Create a new relation in DB between user, board,  template asset UUID and a boolean (`shared` indicator).

**Comment by vrialland** [comment]
Here is the full list of data stored in boards, columns and cards, those exported are prepended with :white_check_mark: 

Board
--------

- :white_check_mark: Title
- :white_check_mark: Description
- URI
- Background image
- Background image position
- Title color
- Comments allowed
- Votes allowed
- Visibility (private or public)
- Show archive column
- Weights activated
- Weights list
- :white_check_mark: Columns
- :white_check_mark: Labels


Label
-------

- :white_check_mark: Title
- :white_check_mark: Color


Column
----------
- :white_check_mark: Title
- Max cards
- :white_check_mark: Cards


Card
-------

- :white_check_mark: Title
- :white_check_mark: Description
- Votes
- :white_check_mark: Labels
- :white_check_mark: Comments (are attached to the user importing the template)
- Assets
- :white_check_mark: Checklists
- Cover image
- :white_check_mark: Due date
- Weight


Comment
------------
- :white_check_mark: Comment


Checklist
------------
- :white_check_mark: Title
- :white_check_mark: Items


Checklist item
------------------
- :white_check_mark: Title
- :white_check_mark: Done

**Comment by vrialland** [comment]
## TODO : update to these values

### Board

- :white_check_mark: Title
- :white_check_mark: Description
- URI
- :white_check_mark: Background image
- :white_check_mark: Background image position
- :white_check_mark: Title color
- :white_check_mark: Comments allowed
- :white_check_mark: Votes allowed
- Visibility (private or public)
- Show archive column
- :white_check_mark: Weights activated
- :white_check_mark: Weights list
- :white_check_mark: Columns
- :white_check_mark: Labels

### Label

- :white_check_mark: Title
- :white_check_mark: Color

### Column

- :white_check_mark: Title
- :white_check_mark: Max cards
- :white_check_mark: Cards

### Card

- :white_check_mark: Title
- :white_check_mark: Description
- Votes
- :white_check_mark: Labels
- Comments
- :white_check_mark: Assets
- :white_check_mark: Checklists
- :white_check_mark: Cover image
- Due date
- :white_check_mark: Weight

### Comment

- :white_check_mark: Comment

### Checklist

- :white_check_mark: Title
- :white_check_mark: Items

### Checklist item

- :white_check_mark: Title
- Done

# Others

- Export overlay:
    - Use radio buttons for export.
    - Put a warning if user exports a board for all users if it is private

- Add a title on the export that will appear in the templates list

**Comment by vrialland** [comment]
Replaced by #97
