### ISSUE TITLE
'<' character in comments

### ISSUE THREAD

**Issue by ygravrand** [Net-ng/kansha#93]
When I use '<' in a comment, some content is silently removed.
This can be annoying, for example:

`Usage: my_prog <mandatory_argument> [optional_argument]`
turns into
`Usage: my_prog  [optional_argument]`

`Activate feature when age < 18 and user is not the captain`
turns into
`Activate feature when age`

**Comment by vrialland** [comment]
HTML is stripped from comments in their validator, that must be the cause to this.
See https://github.com/Net-ng/kansha/blob/master/kansha/comment/comp.py#L88

**Comment by vrialland** [comment]
Moreover, it would be a good idea to allow a 'code' tag in RTE to allow XML, HTML... pasting

**Comment by rtxm** [comment]
Unable to reproduce on latest. Please provide more details:
 * kansha version
 * browser and version
 * OS
Thank you.
