### ISSUE TITLE
Import and export boards

### ISSUE THREAD

**Issue by vrialland** [Net-ng/kansha#97]
# Use case

As a board manager, a user can export the contents of its board and save it as a template.

On a board view in the board menu, an option "Save as template" is available. Clicking on it will open an  overlay on which the user can:
- Enter a title for the template
- Enter a description
- Select if the template is available for all users or the user only

Validating the form will trigger a "Wait animation" and a confirmation message will appear.

On the homepage (boards list), replace the "Create a board" input with a list of existing templates ordered by title.

Choosing one will create a new board and redirect the user on it.

# Export content

Exported data is marked with :white_check_mark:

### Board

- :white_check_mark: Title
- :white_check_mark: Description
- URI
- :white_check_mark: Background image
- :white_check_mark: Background image position
- :white_check_mark: Title color
- :white_check_mark: Comments allowed
- :white_check_mark: Votes allowed
- Visibility (private or public)
- Show archive column
- :white_check_mark: Weights activated
- :white_check_mark: Weights list
- :white_check_mark: Columns
- :white_check_mark: Labels

### Label

- :white_check_mark: Title
- :white_check_mark: Color

### Column

- :white_check_mark: Title
- :white_check_mark: Max cards
- :white_check_mark: Cards

### Card

- :white_check_mark: Title
- :white_check_mark: Description
- Votes
- :white_check_mark: Labels
- Comments
- :white_check_mark: Assets
- :white_check_mark: Checklists
- :white_check_mark: Cover image
- Due date
- :white_check_mark: Weight

### Comment

- Comment

### Checklist

- :white_check_mark: Title
- :white_check_mark: Items

### Checklist item

- :white_check_mark: Title
- Done

# Implementation
- Add a flag on DataBoard to filter templates from boards
- Assets are copied through AssetManager

**Comment by blugand** [comment]
Card - comment is not marked but Comment - Comment is marked. Mistake ?

On the HomePage, Public template and my template should be visually differentiated. Description of the template should be accessible too.

From the HomePage, a user should be able to delete its private templates.

**Comment by vrialland** [comment]
@blugand point 1 was a mistake, fixed.
